from query_processor.processors.letter_maintenance_telegram_query_processor import LetterMaintenanceTelegramQueryProcessor
from query_processor.processors.processing_of_personal_data_telegram_query_processor import PersonalDataTelegramQueryProcessor

query_processors = [
    LetterMaintenanceTelegramQueryProcessor,
    PersonalDataTelegramQueryProcessor
]

__all__ = [query_processors]